server:
  port: 8004
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  hystrix:
    enabled: true
  client:
    config:
      jeecg-provider:
        connectTimeout: 8000
        readTimeout: 3000
