server:
  port: 8003
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    gateway:
      routes:
        - id: jeecg-provider
          uri: lb://jeecg-provider
          predicates:
            - Path=/test/**
        - id: jeecg-config
          uri: lb://jeecg-config
          predicates:
            - Path=/config/**
